version: '3.7'
services:
    ringzer0:
        container_name: ringzer0_coding_challenges
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./src:/usr/dev/ringzer0/coding_challenges/src
        ports:
            - "8008:8008"
        environment:
            - PORT=8008    
            - CHALLENGE_NUMBER=$CHALLENGE_NUMBER
        env_file: ./.env